/-
SPDX-License-Identifier: Unlicense
Developed with Claude (Anthropic).
-/
import DiscreteTime.Neoclassical
import DiscreteTime.Analysis.ScalarMap

/-! # Global dynamics of the discrete-time Solow model, Acemoglu Proposition 2.5

In discrete time a path is generated by iterating the map, so existence and
uniqueness are immediate. The substance is global monotone convergence.
-/

open Set Filter Topology

namespace Solow1956.DiscreteTime

open Solow1956.Neoclassical

variable {f : ℝ → ℝ}

/-- An admissible discrete-time path from positive initial capital. -/
structure IsPath (f : ℝ → ℝ) (s δ γ : ℝ) (k : ℕ → ℝ) : Prop where
  initial_pos : 0 < k 0
  succ : ∀ t, k (t + 1) = next f s δ γ (k t)

/-- The path obtained by iterating the map from `k₀`. -/
noncomputable def path (f : ℝ → ℝ) (s δ γ k₀ : ℝ) (t : ℕ) : ℝ := (next f s δ γ)^[t] k₀

theorem path_zero (s δ γ k₀ : ℝ) : path f s δ γ k₀ 0 = k₀ := rfl

theorem path_succ (s δ γ k₀ : ℝ) (t : ℕ) :
    path f s δ γ k₀ (t + 1) = next f s δ γ (path f s δ γ k₀ t) :=
  Function.iterate_succ_apply' _ _ _

theorem isPath_path {s δ γ k₀ : ℝ} (hk₀ : 0 < k₀) : IsPath f s δ γ (path f s δ γ k₀) :=
  ⟨hk₀, path_succ s δ γ k₀⟩

/-- Uniqueness: a path is determined by its initial stock. -/
theorem path_unique {s δ γ : ℝ} {k l : ℕ → ℝ}
    (hk : ∀ t, k (t + 1) = next f s δ γ (k t)) (hl : ∀ t, l (t + 1) = next f s δ γ (l t))
    (h0 : k 0 = l 0) : k = l := by
  funext t
  induction t with
  | zero => exact h0
  | succ t ih => rw [hk, hl, ih]

theorem IsPath.eq_path {s δ γ : ℝ} {k : ℕ → ℝ} (hk : IsPath f s δ γ k) :
    k = path f s δ γ (k 0) :=
  path_unique hk.succ (path_succ s δ γ (k 0)) rfl

/-- A nonnegative initial stock stays nonnegative; zero stays at zero. -/
theorem path_nonneg (h : Technology f) {s δ γ k₀ : ℝ} (P : Params s δ γ) (hk₀ : 0 ≤ k₀)
    (t : ℕ) : 0 ≤ path f s δ γ k₀ t := by
  induction t with
  | zero => exact hk₀
  | succ t ih => rw [path_succ]; exact next_nonneg h P ih

theorem path_of_zero (h : Technology f) (s δ γ : ℝ) (t : ℕ) : path f s δ γ 0 t = 0 := by
  induction t with
  | zero => rfl
  | succ t ih => rw [path_succ, ih, next_zero h]

/-- Acemoglu Proposition 2.5, with existence and uniqueness explicit: from any
positive stock the path is positive, strictly monotone toward `k*`, stays on its
side of `k*`, and converges to it. -/
theorem general_solow (h : Technology f) {s δ γ k₀ : ℝ} (P : Params s δ γ) (hk₀ : 0 < k₀) :
    ∃ ks : ℝ, 0 < ks ∧ next f s δ γ ks = ks ∧
      (∀ k, 0 < k → next f s δ γ k = k → k = ks) ∧
      ∃ k : ℕ → ℝ, k 0 = k₀ ∧ (∀ t, 0 < k t ∧ k (t + 1) = next f s δ γ (k t)) ∧
        (k₀ < ks → StrictMono k ∧ ∀ t, k t < ks) ∧
        (ks < k₀ → StrictAnti k ∧ ∀ t, ks < k t) ∧
        (k₀ = ks → ∀ t, k t = ks) ∧
        (∀ t, min k₀ ks ≤ k t ∧ k t ≤ max k₀ ks) ∧
        Tendsto k atTop (𝓝 ks) ∧
        (∀ l : ℕ → ℝ, l 0 = k₀ → (∀ t, l (t + 1) = next f s δ γ (l t)) → l = k) := by
  obtain ⟨hks, hfix⟩ := steady_spec h P
  obtain ⟨hpos, hlow, hhigh, hconst, hbd, hlim⟩ := Map.attracting_orbit
    (x := path f s δ γ k₀)
    ((next_strictMono h P).mono Ioi_subset_Ici_self)
    ((next_continuousOn h s δ γ).mono Ioi_subset_Ici_self) hks hfix
    (fun _ hy hlt => next_gt_self h P hy hlt) (fun _ hgt => next_lt_self h P hgt)
    hk₀ (path_succ s δ γ k₀)
  refine ⟨steady h s δ γ, hks, hfix, fun k hk he => (steady_eq h P hk he).symm,
    path f s δ γ k₀, rfl, fun t => ⟨hpos t, path_succ s δ γ k₀ t⟩,
    hlow, hhigh, hconst, hbd, hlim, fun l hl0 hl => ?_⟩
  exact path_unique hl (path_succ s δ γ k₀) hl0

/-- Every admissible path has the full Proposition 2.5 behaviour relative to `k*`. -/
theorem IsPath.orbit (h : Technology f) {s δ γ : ℝ} (P : Params s δ γ) {k : ℕ → ℝ}
    (hk : IsPath f s δ γ k) :
    (∀ t, 0 < k t) ∧
      (k 0 < steady h s δ γ → StrictMono k ∧ ∀ t, k t < steady h s δ γ) ∧
      (steady h s δ γ < k 0 → StrictAnti k ∧ ∀ t, steady h s δ γ < k t) ∧
      (k 0 = steady h s δ γ → ∀ t, k t = steady h s δ γ) ∧
      (∀ t, min (k 0) (steady h s δ γ) ≤ k t ∧ k t ≤ max (k 0) (steady h s δ γ)) ∧
      Tendsto k atTop (𝓝 (steady h s δ γ)) :=
  Map.attracting_orbit ((next_strictMono h P).mono Ioi_subset_Ici_self)
    ((next_continuousOn h s δ γ).mono Ioi_subset_Ici_self) (steady_spec h P).1
    (steady_spec h P).2 (fun _ hy hlt => next_gt_self h P hy hlt)
    (fun _ hgt => next_lt_self h P hgt) hk.initial_pos hk.succ

theorem IsPath.pos (h : Technology f) {s δ γ : ℝ} (P : Params s δ γ) {k : ℕ → ℝ}
    (hk : IsPath f s δ γ k) (t : ℕ) : 0 < k t :=
  (hk.orbit h P).1 t

theorem IsPath.tendsto (h : Technology f) {s δ γ : ℝ} (P : Params s δ γ) {k : ℕ → ℝ}
    (hk : IsPath f s δ γ k) : Tendsto k atTop (𝓝 (steady h s δ γ)) :=
  (hk.orbit h P).2.2.2.2.2

theorem IsPath.bounds (h : Technology f) {s δ γ : ℝ} (P : Params s δ γ) {k : ℕ → ℝ}
    (hk : IsPath f s δ γ k) (t : ℕ) :
    min (k 0) (steady h s δ γ) ≤ k t ∧ k t ≤ max (k 0) (steady h s δ γ) :=
  (hk.orbit h P).2.2.2.2.1 t

/-- Output and consumption converge along any path; positive consumption needs `s < 1`. -/
theorem output_consumption_limit (h : Technology f) {s δ γ : ℝ} (P : Params s δ γ)
    {k : ℕ → ℝ} (hk : IsPath f s δ γ k) :
    Tendsto (fun t => f (k t)) atTop (𝓝 (f (steady h s δ γ))) ∧
      Tendsto (fun t => (1 - s) * f (k t)) atTop (𝓝 ((1 - s) * f (steady h s δ γ))) := by
  have hy := (h.differentiable _ (steady_spec h P).1).continuousAt.tendsto.comp (hk.tendsto h P)
  exact ⟨hy, hy.const_mul (1 - s)⟩

end Solow1956.DiscreteTime
